# Generated by Django 5.0.2 on 2024-02-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
    ]
