# Generated by Django 5.0.3 on 2024-03-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingFinderApp', '0003_alter_parkingspace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
