# Generated by Django 5.0.3 on 2024-03-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingFinderApp', '0004_alter_parkingspace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
